### ISSUE TITLE
Removing old code for rescaling tiles to 256x256

### ISSUE THREAD

**Issue by bjmdev** [telemaxx/mapsforgesrv_with_gradle#4]
Hi,

class MapsforgeHandler contains the following code (lines 260 to 270):
`if (image.getWidth() != 256) {
			final BufferedImage bufferedImage = new BufferedImage(256, 256, BufferedImage.TYPE_INT_ARGB);
			final Graphics2D graphics2D = bufferedImage.createGraphics();
			graphics2D.setComposite(AlphaComposite.Src);
			graphics2D.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
			graphics2D.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
			// graphics2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
			graphics2D.drawImage(image, 0, 0, 256, 256, null);
			graphics2D.dispose();
			image = bufferedImage;
		}`

I think this was a hack to solve https://mobac.sourceforge.io/forum/viewtopic.php?t=817 and is IMHO not necessary anymore with recent Mapsforge versions. It should be removed as it is consuming unnecessary CPU time. Any thoughts on this?

Thank you very much!

**Comment by telemaxx** [comment]
i will try this week. would reduce the imports a lot...

**Comment by telemaxx** [comment]
merged and tested. Thank you!
